### PR TITLE
Use params attribute of requests.Session

### PR DESCRIPTION
**Pull request by Ruwann**
Use `params` attribute of `requests.Session()` instead of manually constructing the query parameters in the URL.

### CODE REVIEW

**Review by JeroenProoth — APPROVED** [review]
Great alternative!

**Review by JeroenProoth — CHANGES_REQUESTED** [review]
Please update the __init__ in account.py to conform with your other changes.

**Comment by JeroenProoth** [comment]
Also, please resolve the merge conflict. :(

**Comment by Ruwann** [comment]
I have updated the account.py as well and resolved the merge conflicts!

**Pull request merged**
